### ISSUE TITLE
create a database model/schema

### ISSUE THREAD

**Issue by ajv7683** [Scrum-and-coke-development-team/suppliers#1]
**As a** User  
 **I need** a database schema to be developed  
 **So that** there is an organized method to interact with the database  
   
 ### Details and Assumptions
 * needs to be standardized across the organization
   
 ### Acceptance Criteria  
 * database model can be used widely across the team

 ```gherkin
 Given that I am a user interacting with the database
 When I go to interact with the database
 Then I should always have standardized inputs and outputs
 ```

**Comment by mw1984** [comment]
Second priority as need way to be able to find and store resource
