### ISSUE TITLE
List supplier resources

### ISSUE THREAD

**Issue by DavidRestrepo11** [Scrum-and-coke-development-team/suppliers#10]
**As a user
 **I need list the supplier resources  
 **So that I can filter the supplier's products
   
 ### Details and Assumptions
 * Users want to check different products from different suppliers and need an easy way to visualizing them.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that users want to list supplier resources
 When the user selects a supplier
 Then the user should observe all the pertinent resources
 ```

**Comment by mw1984** [comment]
lowest priority as user can still navigate resources without having a list
