### ISSUE TITLE
read your supplier resource

### ISSUE THREAD

**Issue by mig9206** [Scrum-and-coke-development-team/suppliers#5]
As a User
I need to be able to pull data from the supplier database without modifying it
So that I can read and interpret the data and respond to data requests
   
 ### Details and Assumptions
 * There should be an already established database with supplier information

 ### Acceptance Criteria  
 * All supplier data can be pulled from the supplier database by all team members without modifying it

 ```gherkin
 Given that I am a user interacting with the database
 When I read the supplier resource (database)
 Then the relevant supplier data should be pulled
 ```

**Comment by mw1984** [comment]
suppliers need ability to access and review resource
