### ISSUE TITLE
create database model

### ISSUE THREAD

**Issue by ajv7683** [Scrum-and-coke-development-team/suppliers#6]
**As a** user  
 **I need** to be interacting with a database that has a model 
 **So that** supplier information is standardized in the database  
   
 ### Details and Assumptions
 * this model should be standard to suppliers, no exceptions
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I am interacting with the database
 When I use one of the CRUD interactions
 Then I am able to interact in a standardized fashion
 ```

**Comment by mw1984** [comment]
Highest priority as it involves initial build
