### ISSUE TITLE
Create a microservice

### ISSUE THREAD

**Issue by ethan17levy** [Scrum-and-coke-development-team/suppliers#7]
**As a** User  
 **I need** to be able to use a microservice skeleton 
 **So that**   service are available in an intuitive format
   
 ### Details and Assumptions
 * The microservice skeleton will enable users to interact with the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a microservice skeleton is required
 When a microservice needs to be performed 
 Then the user should be able to interact with the database with microservices
 ```

**Comment by mw1984** [comment]
For users, they need services to interact with. First point of discovery
