### ISSUE TITLE
delete supplier resource 

### ISSUE THREAD

**Issue by DavidRestrepo11** [Scrum-and-coke-development-team/suppliers#8]
**As a supplier
 **I need to delete a resource
 **So that I can eliminate the resources that are not useful anymore
   
 ### Details and Assumptions
 * The supplier needs to manipulate their own resources on our data base
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that users want to eliminate a resource
 When they delete the item
 Then they should not see it anymore.
 ```

**Comment by mw1984** [comment]
Rather than updating resources to non existent when updating, will be enhancement for user to remove resource
