### ISSUE TITLE
Create a Supplier Resource

### ISSUE THREAD

**Issue by ethan17levy** [Scrum-and-coke-development-team/suppliers#9]
**As a** Supplier  
 **I need** be able to add an item or resource
 **So that** that item can be sold on the ecommerce site.  
   
 ### Details and Assumptions
 * Suppliers will need to be able to add their own items to the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a supplier wants to add an item to the Ecommerce
 When that supplier adds the item to the database
 Then the item will be available for sale on the Ecommerce Site
 ```

**Comment by mw1984** [comment]
Once the plan is built, need to have initial resource available to get off ground
